apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: zppu38zrr-nodejs 
  janus-idp.io/tekton: zppu38zrr-nodejs
  backstage.io/kubernetes-id: zppu38zrr-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: zppu38zrr-nodejs
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  