apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: zppu38zrr-nodejs
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: zppu38zrr-nodejs 
  name: zppu38zrr-nodejs
spec:
  ports:
  - port: 3001 
    targetPort: 3001 
  selector:
    app.kubernetes.io/instance: zppu38zrr-nodejs 
